### ISSUE TITLE
Error while finding module specification for 'deadseeker.action'

### ISSUE THREAD

**Issue by aceberle** [ScholliYT/Broken-Links-Crawler-Action#10]
Using the new 3.0.0 version, my github workflow is failing with the following error:
`/usr/local/bin/python: Error while finding module specification for 'deadseeker.action' (ModuleNotFoundError: No module named 'deadseeker')`

This is odd because running "act" on the code appears to work fine.

**Comment by aceberle** [comment]
#11 may fix the problem

**Comment by ScholliYT** [comment]
Ugh, I thought I tested the new v3 with my daily running action.

I'll try to test it with your changes here: https://github.com/ScholliYT/Broken-Links-Crawler-Action/releases/tag/v3.0.1-beta

**Comment by aceberle** [comment]
Interesting, is there any way you can confirm whether 3.0.0 ever worked for you?  I only just tried it for the first time today and that's when I got the module error.

It's very disappointing that running it in github workflow would produce a different result than running it in Docker

**Comment by ScholliYT** [comment]
Fixed in https://github.com/ScholliYT/Broken-Links-Crawler-Action/releases/tag/v3.0.1
