### ISSUE TITLE
Display page containing broken link

### ISSUE THREAD

**Issue by szepeviktor** [ScholliYT/Broken-Links-Crawler-Action#18]
I've happily stared using your software :)

```
Error: ClientResponseError: 404 - https://www.bankitamas.hu/hirdeteacutes.html
```

But unable to find the location of broken links.
Please consider displaying the URL of the containing page.
Thanks.

**Comment by ScholliYT** [comment]
Hi @szepeviktor, 

You can have a look at #24. This implements logging of the page containing a broken link. What's your opinion on this?

**Comment by szepeviktor** [comment]
Thank you!
That is more than okay for me.

**Comment by ScholliYT** [comment]
You might want to give the most recent version (v3.1.1) a try @szepeviktor  :smiley: The feature is included there.

**Comment by szepeviktor** [comment]
Thank you.
