### ISSUE TITLE
Some relative links detected as broken false positive

### ISSUE THREAD

**Issue by banagale** [ScholliYT/Broken-Links-Crawler-Action#5]
I do not have time to figure out what was causing it, but as a word of warning I was having _some_ but relative links getting falsely detected as broken.

Rather than fix it, I just changed to root-relative links for them and deadseeker stopped complaining.

**Comment by ScholliYT** [comment]
Thanks for the info. I could imagine that things like ~/content/subpage.html referring to ~/content/docs/doc.html with `href="docs/doc.html"` were causing problems. Is that what you mean by relative links?

**Comment by banagale** [comment]
Sure, realize even a bit more info would be helpful here. 

```  <li><a href="../product/index.html">PRODUCT</a></li>
           <li><a href="/forge/product/index.html">PRODUCT</a></li>
```
The first link above resolved fine in production, but was determined as an invalid link by deadseeker. 

The second is also valid in production but passes okay. 

I did make a few passes at both adding a reference to the page that has the broken  link (which I needed as I could not find it). 

But I was working on the original deadseeker master and realized this had forked then ran out of time.
