### ISSUE TITLE
how do I ignore codeblocks?

### ISSUE THREAD

**Issue by clubanderson** [ScholliYT/Broken-Links-Crawler-Action#59]
Some code blocks have output in them that include UIDs that always fail the spellcheck.

**Comment by ScholliYT** [comment]
Can you give or link an example?

**Comment by clubanderson** [comment]
apmziqj9p9fqlflm-mb-bf452e1f-45a0-4d5d-b35c-ef1ece2879ba" mbwsCluster="yk9a66vjms1pi8hu" bindingName="bind-edge" resourceVersion="914"
...


https://docs.kubestellar.io/main/Coding%20Milestones/PoC2023q1/placement-translator/

**Comment by clubanderson** [comment]
Results of my latest run on our main branch

https://github.com/kcp-dev/edge-mc/actions/runs/5217127053/jobs/9416626789

**Comment by ScholliYT** [comment]
Hey, are you sure this is related to the Broken links crawler? 
It looks like this is a problem of https://github.com/rojopolis/spellcheck-github-actions. Please correct me if I am wrong.

**Comment by clubanderson** [comment]
Oh boy. My bad. I'm sorry. This is spellcheck related. Why on earth did I open an issue with you. I'm so sorry. My apologies. Let me close this out.
